server:
  port: 10000
  servlet:
    session:
      timeout: 30m

spring:
  application:
    name: gulimall-product
  datasource:
    username: root
    password: 123123
    url: jdbc:mysql://192.168.120.129:3306/gulimall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml